### ISSUE TITLE
Wrong casing breaking some servers

### ISSUE THREAD

**Issue by sanderha** [littlegiant/silverstripe-security-theme#1]
Hello,
Thanks for the cool module :-)

This line in `SecurityPage.ss`: 
`<% include LittleGiant/SilverstripeSecurityTheme/Form %>`
Should be
`<% include LittleGiant/SilverStripeSecurityTheme/Form %>`
Same issue for a few other templates.
If done a PR

**Comment by sanderha** [comment]
#2

**Comment by stevie-mayhew** [comment]
Thanks @sanderha
